Update function.rst
When I test this example in django-river-v3.2.0, it will raise following execption:

```
'TransitionApprovalMeta' object has no attribute 'source_state'
Traceback (most recent call last):
  ...
    self.callback_function.get()(context)
  File "<string>", line 46, in _wrapper
  File "<string>", line 39, in handle
  File "<string>", line 10, in _handle_my_transitions
AttributeError: 'TransitionApprovalMeta' object has no attribute 'source_state'
```

I think maybe some api have changed and document have not updated in time. Please check it, thank you.